// napoveda.js - slovnik jazyka CeskyWeb
// Jeden zdroj pravdy: z tohoto seznamu se generuje napoveda, naseptavac i zvyraznovani.

const NAPOVEDA = {
  barvy: ['bila', 'cerna', 'cervena', 'modra', 'zelena', 'zluta', 'oranzova', 'fialova', 'ruzova', 'seda', 'tyrkysova', 'hnueda'],

  barevnik: {
    bila: '#ffffff',
    cerna: '#101418',
    cervena: '#e03131',
    modra: '#2f6fed',
    zelena: '#2f9e44',
    zluta: '#f2c037',
    oranzova: '#f08c00',
    fialova: '#7048e8',
    ruzova: '#e64980',
    seda: '#868e96',
    tyrkysova: '#15aabf',
    hnueda: '#8a5a2b'
  },

  prikazy: [
    // ---- Zaklad ----
    { klic: 'stranka', skupina: 'Zaklad', popis: 'Nazev stranky v zalozce prohlizece', ukazka: 'stranka "Moje stranka"', vlozit: 'stranka ""', odKonce: 1 },
    { klic: 'vzhled', skupina: 'Zaklad', popis: 'Vzhled cele stranky', ukazka: 'vzhled svetly', hodnoty: ['svetly', 'tmavy', 'barevny', 'minimal'] },
    { klic: 'barva-pozadi', skupina: 'Zaklad', popis: 'Barva pozadi stranky', ukazka: 'barva-pozadi bila' },
    { klic: 'barva-textu', skupina: 'Zaklad', popis: 'Barva vseho textu', ukazka: 'barva-textu cerna' },
    { klic: 'zarovnani', skupina: 'Zaklad', popis: 'Zarovnani obsahu', ukazka: 'zarovnani stred', hodnoty: ['vlevo', 'stred', 'vpravo'] },
    { klic: 'font', skupina: 'Zaklad', popis: 'Velikost pisma', ukazka: 'font velky', hodnoty: ['maly', 'normalni', 'velky'] },

    // ---- Obsah ----
    { klic: 'nadpis', skupina: 'Obsah', popis: 'Velky nadpis. Uvozovky psat nemusis', ukazka: 'nadpis Vitej na mem webu', vlozit: 'nadpis ', odKonce: 0 },
    { klic: 'podnadpis', skupina: 'Obsah', popis: 'Mensi nadpis. Uvozovky psat nemusis', ukazka: 'podnadpis O mne', vlozit: 'podnadpis ', odKonce: 0 },
    { klic: 'text', skupina: 'Obsah', popis: 'Odstavec textu. Muzes mu dat #nazev a menit ho pozdeji', ukazka: 'text Ahoj, jmenuju se Petr.', vlozit: 'text ', odKonce: 0 },
    { klic: 'pridej', skupina: 'Obsah', popis: 'Odstavec s hodnotou promenne nebo policka', ukazka: 'pridej $skore' },
    { klic: 'tlacitko', skupina: 'Obsah', popis: 'Tlacitko, ktere spusti akci', ukazka: 'tlacitko "Posli" -> odesli', vlozit: 'tlacitko "" -> ', odKonce: 5 },
    { klic: 'odkaz', skupina: 'Obsah', popis: 'Odkaz na jinou adresu', ukazka: 'odkaz "Google" -> "https://google.com"', vlozit: 'odkaz "" -> ""', odKonce: 7 },
    { klic: 'obrazek', skupina: 'Obsah', popis: 'Obrazek z adresy', ukazka: 'obrazek "https://..." "popis"', vlozit: 'obrazek "" ""', odKonce: 4 },
    { klic: 'vstup', skupina: 'Obsah', popis: 'Policko, do ktereho muze clovek psat', ukazka: 'vstup #jmeno "Tvoje jmeno"', vlozit: 'vstup # ""', odKonce: 1 },
    { klic: 'cislo', skupina: 'Obsah', popis: 'Policko pro cislo', ukazka: 'cislo #vek "Kolik ti je"', vlozit: 'cislo # ""', odKonce: 1 },
    { klic: 'zaskrtavatko', skupina: 'Obsah', popis: 'Zaskrtavaci policko. V podmince zjistis hodnotou 1', ukazka: 'zaskrtavatko #souhlas "Souhlasim"', vlozit: 'zaskrtavatko # ""', odKonce: 1 },
    { klic: 'vyber', skupina: 'Obsah', popis: 'Rozbalovaci seznam. Moznosti se pisou dovnitr', ukazka: 'vyber #barva', vlozit: 'vyber #\n\nkonec', odKonce: 7 },
    { klic: 'moznost', skupina: 'Obsah', popis: 'Jedna volba ve vyberu', ukazka: 'moznost "Cervena"', vlozit: 'moznost ""', odKonce: 1 },
    { klic: 'mezera', skupina: 'Obsah', popis: 'Prazdna mezera mezi prvky', ukazka: 'mezera' },

    // ---- Stavebni bloky ----
    { klic: 'komponenta', skupina: 'Stavebni bloky', popis: 'Pojmenovany blok, ktery muzes vlozit na vice mist. Uvnitr nedavej jmena #, kdyz ji vkladas vickrat', ukazka: 'komponenta hlavicka', vlozit: 'komponenta \n\nkonec', odKonce: 7 },
    { klic: 'vloz', skupina: 'Stavebni bloky', popis: 'Vlozi komponentu. Funguje i kdyz je definovana az pozdeji v kodu', ukazka: 'vloz hlavicka' },

    // ---- Vicestrankovy web ----
    { klic: 'podstranka', skupina: 'Vicestrankovy web', popis: 'Dalsi stranka webu. Menu se udela samo prikazem menu', ukazka: 'podstranka #o-nas O nas', vlozit: 'podstranka # \n\nkonec', odKonce: 7 },
    { klic: 'menu', skupina: 'Vicestrankovy web', popis: 'Horni menu s odkazy na vsechny podstranky. Vzdy se ukaze nahore', ukazka: 'menu' },
    { klic: 'jdi-na', skupina: 'Vicestrankovy web', popis: 'Prepnne na jinou stranku webu', ukazka: 'jdi-na #o-nas' },
    { klic: 'platno', skupina: 'Obsah', popis: 'Kreslici platno, na ktere se kresli tvary', ukazka: 'platno #kresba 400, 300', vlozit: 'platno # 400, 300', odKonce: 12 },
    { klic: 'oddelovac', skupina: 'Obsah', popis: 'Vodorovna cara pres celou sirku', ukazka: 'oddelovac' },
    { klic: 'karta', skupina: 'Obsah', popis: 'Ramecek okolo obsahu', ukazka: 'karta' },
    { klic: 'blok', skupina: 'Obsah', popis: 'Skupina prvku bez ramecku', ukazka: 'blok' },
    { klic: 'seznam', skupina: 'Obsah', popis: 'Seznam s odrazkami', ukazka: 'seznam' },
    { klic: 'polozka', skupina: 'Obsah', popis: 'Jedna odrazka v seznamu. Uvozovky psat nemusis', ukazka: 'polozka Prvni vec', vlozit: 'polozka ', odKonce: 0 },
    { klic: 'konec', skupina: 'Obsah', popis: 'Ukonci blok, akci nebo podminku', ukazka: 'konec' },

    // ---- Akce a logika ----
    { klic: 'akce', skupina: 'Akce', popis: 'Pojmenovana akce, kterou spusti tlacitko', ukazka: 'akce odesli', vlozit: 'akce nazev\n\nkonec', odKonce: 5 },
    { klic: 'kdyz', skupina: 'Akce', popis: 'Podminka - neco se stane jen kdyz plati', ukazka: 'kdyz #skore > 10', vlozit: 'kdyz  \n\nkonec', odKonce: 7 },
    { klic: 'jinak', skupina: 'Akce', popis: 'Co se stane, kdyz podminka neplati', ukazka: 'jinak' },
    { klic: 'promenna', skupina: 'Akce', popis: 'Ulozi hodnotu pod jmeno, ktere zacina znakem $', ukazka: 'promenna $skore = 0', vlozit: 'promenna $ = 0', odKonce: 4 },
    { klic: 'nastav', skupina: 'Akce', popis: 'Zmeni obsah prvku nebo hodnotu promenne', ukazka: 'nastav #vysledek "Hotovo"' },
    { klic: 'pridej-do', skupina: 'Akce', popis: 'Prida text na konec prvku', ukazka: 'pridej-do #vypis "Dalsi radek "' },
    { klic: 'skryj', skupina: 'Akce', popis: 'Skryje prvek', ukazka: 'skryj #tajne' },
    { klic: 'zobraz', skupina: 'Akce', popis: 'Zobrazi drive skryty prvek', ukazka: 'zobraz #tajne' },
    { klic: 'obarvi', skupina: 'Akce', popis: 'Zmeni barvu textu prvku', ukazka: 'obarvi #nazev cervena' },
    { klic: 'okno', skupina: 'Akce', popis: 'Ukaze hlasku v malem okne', ukazka: 'okno "Ahoj!"' },
    { klic: 'prejdi', skupina: 'Akce', popis: 'Posle cloveka na jinou adresu', ukazka: 'prejdi "https://www.seznam.cz"' },
    { klic: 'posun', skupina: 'Akce', popis: 'Posune prvek po strance. Dve hodnoty oddel carkou', ukazka: 'posun #terc 20, 10' },
    { klic: 'velikost', skupina: 'Akce', popis: 'Nastavi sirku prvku v bodech', ukazka: 'velikost #obrazek 300' },
    { klic: 'zapis', skupina: 'Akce', popis: 'Ulozi hodnotu do prohlizece, zustane i po zavreni', ukazka: 'zapis "skore" $skore' },
    { klic: 'nacti', skupina: 'Akce', popis: 'Nacte ulozenou hodnotu do promenne', ukazka: 'nacti $skore "skore"' },
    { klic: 'opakuj', skupina: 'Akce', popis: 'Opakuje akci dokola. Druhe cislo je cas v tisicinach sekundy', ukazka: 'opakuj tik 1000' },
    { klic: 'klavesa', skupina: 'Akce', popis: 'Spusti akci po stisku klavesy', ukazka: 'klavesa "a" doleva' },
    { klic: 'pri-stisku', skupina: 'Akce', popis: 'Spusti akci, kdyz clovek klikne na prvek', ukazka: 'pri-stisku #karta klik' },
    { klic: 'pri-najeti', skupina: 'Akce', popis: 'Spusti akci, kdyz clovek najede mysi na prvek', ukazka: 'pri-najeti #karta nabehni' },
    { klic: 'pri-zmene', skupina: 'Akce', popis: 'Spusti akci, kdyz clovek zmeni obsah policka', ukazka: 'pri-zmene #jmeno zmena' },
    { klic: 'smaz', skupina: 'Akce', popis: 'Odstrani prvek ze stranky', ukazka: 'smaz #karta' },
    { klic: 'pozadi', skupina: 'Akce', popis: 'Barva pozadi prvku', ukazka: 'pozadi #karta zluta' },
    { klic: 'ohranic', skupina: 'Akce', popis: 'Ramecek okolo prvku. Cislo je tloustka v bodech', ukazka: 'ohranic #karta cervena 3' },
    { klic: 'zaobli', skupina: 'Akce', popis: 'Zakulati rohy prvku', ukazka: 'zaobli #karta 16' },
    { klic: 'pruhlednost', skupina: 'Akce', popis: 'Pruhlednost prvku od 0 do 1', ukazka: 'pruhlednost #karta 0.5' },
    { klic: 'otoc', skupina: 'Akce', popis: 'Otoci prvek o zadany pocet stupnu', ukazka: 'otoc #karta 45' },
    { klic: 'vycisti', skupina: 'Kresleni', popis: 'Smaze vsechno, co je na platne nakreslene', ukazka: 'vycisti #kresba' },
    { klic: 'obdelnik', skupina: 'Kresleni', popis: 'Obdelnik na platno. Hodnoty oddel carkou, barva je dobrovolna', ukazka: 'obdelnik #kresba 10, 20, 50, 30, modra' },
    { klic: 'kruh', skupina: 'Kresleni', popis: 'Kruh na platno. Stred a polomer, barva dobrovolna', ukazka: 'kruh #kresba 60, 60, 20, cervena' },
    { klic: 'cara', skupina: 'Kresleni', popis: 'Cara z jednoho bodu do druheho', ukazka: 'cara #kresba 0, 0, 100, 100, cerna' },
    { klic: 'text-platno', skupina: 'Kresleni', popis: 'Text napsany na platno', ukazka: 'text-platno #kresba 10, 20, Ahoj' },
    { klic: 'barva-platna', skupina: 'Kresleni', popis: 'Barva, kterou se kresli, kdyz ji u tvaru nezadas', ukazka: 'barva-platna #kresba zelena' },
    { klic: 'tloustka', skupina: 'Kresleni', popis: 'Tloustka cary na platne', ukazka: 'tloustka #kresba 4' },

    // ---- Cykly a seznamy ----
    { klic: 'krat', skupina: 'Cykly', popis: 'Zopakuje neco nekolikrat. Ukonci se prikazem konec', ukazka: 'krat 5', vlozit: 'krat \n\nkonec', odKonce: 8 },
    { klic: 'dokud', skupina: 'Cykly', popis: 'Opakuje dokola, dokud plati podminka', ukazka: 'dokud $pocet < 10', vlozit: 'dokud  \n\nkonec', odKonce: 8 },
    { klic: 'pro-kazdou', skupina: 'Cykly', popis: 'Projde vsechny hodnoty v seznamu jednu po druhe', ukazka: 'pro-kazdou $x v $seznam', vlozit: 'pro-kazdou $ v $seznam\n\nkonec', odKonce: 17 },
    { klic: 'prerus', skupina: 'Cykly', popis: 'Utne cyklus a pokracuje dal za nim', ukazka: 'prerus' },
    { klic: 'pokracuj', skupina: 'Cykly', popis: 'Preskoci zbytek a skoci na dalsi opakovani', ukazka: 'pokracuj' },
    { klic: 'pridej-do-pole', skupina: 'Seznamy', popis: 'Prida hodnotu na konec seznamu', ukazka: 'pridej-do-pole $seznam $skore' },
    { klic: 'vycisti-pole', skupina: 'Seznamy', popis: 'Vyprazdni cely seznam', ukazka: 'vycisti-pole $seznam' },
    { klic: 'serad', skupina: 'Seznamy', popis: 'Seradi seznam od nejmensiho po nejvetsi', ukazka: 'serad $seznam' },
    { klic: 'odstran', skupina: 'Seznamy', popis: 'Odstrani hodnotu ze seznamu na pozici. Pocita se od nuly', ukazka: 'odstran $seznam 0' },
    { klic: 'cekej', skupina: 'Akce', popis: 'Pocka a pak spusti akci. Cas je v tisicinach sekundy', ukazka: 'cekej 1000 zpracuj' },
    { klic: 'prehraj', skupina: 'Akce', popis: 'Prehraje zvuk z adresy', ukazka: 'prehraj "https://adresa-zvuk.mp3"' },

    // ---- Funkce do vyrazu ----
    { klic: 'nahodne', skupina: 'Funkce', popis: 'Nahodne cele cislo od-do', ukazka: 'promenna $kostka = nahodne(1, 6)' },
    { klic: 'delka', skupina: 'Funkce', popis: 'Pocet znaku v textu', ukazka: 'nastav #pocet delka(#jmeno)' },
    { klic: 'na-cislo', skupina: 'Funkce', popis: 'Prevede text na cislo', ukazka: 'nastav $x na-cislo(#vek)' },
    { klic: 'zaokrouhli', skupina: 'Funkce', popis: 'Zaokrouhli cislo na cele', ukazka: 'nastav #c zaokrouhli(3.6)' },
    { klic: 'minimalne', skupina: 'Funkce', popis: 'Mensi z dvou hodnot', ukazka: 'nastav #z minimalne(#a, #b)' },
    { klic: 'maximalne', skupina: 'Funkce', popis: 'Vetsi z dvou hodnot', ukazka: 'nastav #z maximalne(#a, #b)' },
    { klic: 'text', skupina: 'Funkce', popis: 'Prevede cislo na text', ukazka: 'nastav #t text(#cislo)' },
    { klic: 'mocnina', skupina: 'Funkce', popis: 'Umocni cislo na druhe cislo', ukazka: 'nastav #v mocnina(2, 8)' },
    { klic: 'prumer', skupina: 'Funkce', popis: 'Prumer dvou cisel', ukazka: 'nastav #v prumer(#a, #b)' },
    { klic: 'absolutne', skupina: 'Funkce', popis: 'Vzdalenost cisla od nuly', ukazka: 'nastav #v absolutne(-5)' },
    { klic: 'nahodne-barva', skupina: 'Funkce', popis: 'Nahodna barva ze seznamu', ukazka: 'obarvi #nazev nahodne-barva()' },
    { klic: 'velka-pismena', skupina: 'Funkce', popis: 'Prevede text na VELKA pismena', ukazka: 'nastav #v velka-pismena(#jmeno)' },
    { klic: 'mala-pismena', skupina: 'Funkce', popis: 'Prevede text na mala pismena', ukazka: 'nastav #v mala-pismena(#jmeno)' },
    { klic: 'obsahuje', skupina: 'Funkce', popis: 'Vrati 1, kdyz text obsahuje hledany text, jinak 0', ukazka: 'kdyz obsahuje(#text, "ano") = 1' },
    { klic: 'koren', skupina: 'Funkce', popis: 'Druha odmocnina cisla', ukazka: 'nastav #v koren(16)' },
    { klic: 'dole', skupina: 'Funkce', popis: 'Zaokrouhli dolu na cele cislo', ukazka: 'nastav #v dole(3.9)' },
    { klic: 'nahoru', skupina: 'Funkce', popis: 'Zaokrouhli nahoru na cele cislo', ukazka: 'nastav #v nahoru(3.1)' },
    { klic: 'zbytek', skupina: 'Funkce', popis: 'Zbytek po deleni', ukazka: 'nastav #v zbytek(10, 3)' },
    { klic: 'pi', skupina: 'Funkce', popis: 'Cislo pi pro pocitani s kruhy', ukazka: 'nastav #v pi()' },
    { klic: 'sinus', skupina: 'Funkce', popis: 'Sinus uhlu v radianech', ukazka: 'nastav #v sinus(0)' },
    { klic: 'kosinus', skupina: 'Funkce', popis: 'Kosinus uhlu v radianech', ukazka: 'nastav #v kosinus(0)' },
    { klic: 'orez', skupina: 'Funkce', popis: 'Odstrani mezery na zacatku a na konci textu', ukazka: 'nastav #v orez(#jmeno)' },
    { klic: 'cast', skupina: 'Funkce', popis: 'Vybere cast textu od-do', ukazka: 'nastav #v cast(#jmeno, 0, 3)' },
    { klic: 'najdi', skupina: 'Funkce', popis: 'Najde, na ktere pozici je hledany text', ukazka: 'nastav #v najdi(#jmeno, "a")' },
    { klic: 'nahrad', skupina: 'Funkce', popis: 'Nahradi vsechny vyskyty textu jinym textem', ukazka: 'nastav #v nahrad(#jmeno, "a", "b")' },
    { klic: 'zacina', skupina: 'Funkce', popis: 'Vrati 1, kdyz text zacina hledanym textem', ukazka: 'kdyz zacina(#jmeno, "Pa") = 1' },
    { klic: 'konci', skupina: 'Funkce', popis: 'Vrati 1, kdyz text konci hledanym textem', ukazka: 'kdyz konci(#jmeno, "ova") = 1' },
    { klic: 'opakuj-text', skupina: 'Funkce', popis: 'Zopakuje text nekolikrat za sebou', ukazka: 'nastav #v opakuj-text("-", 20)' },
    { klic: 'zaokrouhli-na', skupina: 'Funkce', popis: 'Zaokrouhli na zadany pocet desetinnych mist', ukazka: 'nastav #v zaokrouhli-na(3.14159, 2)' },
    { klic: 'tangens', skupina: 'Funkce', popis: 'Tangens uhlu v radianech', ukazka: 'nastav #v tangens(1)' },
    { klic: 'logaritmus', skupina: 'Funkce', popis: 'Prirozeny logaritmus cisla', ukazka: 'nastav #v logaritmus(10)' },
    { klic: 'pole', skupina: 'Funkce', popis: 'Prazdny seznam hodnot', ukazka: 'promenna $cisla = pole()' },
    { klic: 'vezmi', skupina: 'Funkce', popis: 'Vezme hodnotu ze seznamu na pozici. Pocita se od nuly', ukazka: 'nastav #v vezmi($seznam, 0)' },
    { klic: 'pocet', skupina: 'Funkce', popis: 'Kolik hodnot je v seznamu', ukazka: 'nastav #v pocet($seznam)' },
    { klic: 'spoj-pole', skupina: 'Funkce', popis: 'Spoji seznam do jednoho textu', ukazka: 'nastav #v spoj-pole($seznam, \", \")' },
    { klic: 'slova', skupina: 'Funkce', popis: 'Rozdeli text na seznam slov', ukazka: 'promenna $s = slova(\"ano ne mozna\")' },
    { klic: 'nahodne-z-pole', skupina: 'Funkce', popis: 'Nahodna hodnota ze seznamu', ukazka: 'nastav #v nahodne-z-pole($seznam)' },
    { klic: 'obsahuje-pole', skupina: 'Funkce', popis: 'Vrati 1, kdyz seznam obsahuje hodnotu', ukazka: 'kdyz obsahuje-pole($seznam, \"ano\") = 1' },
    { klic: 'cislo-text', skupina: 'Funkce', popis: 'Prevede cislo na text', ukazka: 'nastav #v cislo-text(42)' },
    { klic: 'desetinna-cast', skupina: 'Funkce', popis: 'Jen cast za desetinnou carkou', ukazka: 'nastav #v desetinna-cast(3.75)' },
    { klic: 'znak', skupina: 'Funkce', popis: 'Jeden znak z textu na pozici. Pocita se od nuly', ukazka: 'nastav #v znak(\"ahoj\", 1)' }
  ],

  priklady: [
    {
      nazev: '1 - Jednoducha stranka',
      kod: [
        '// Prvni web v jazyce CeskyWeb',
        '// Radky zacinajici // jsou jen poznamky pro tebe.',
        '',
        'stranka "Muj prvni web"',
        'vzhled svetly',
        '',
        'nadpis "Ahoj svete"',
        'text "Tohle je moje prvni stranka. Zkus zmenit text a stiskni Spustit."',
        '',
        'karta',
        '  podnadpis "Co umim"',
        '  seznam',
        '    polozka "Nadpisy a texty"',
        '    polozka "Tlacitka a odkazy"',
        '    polozka "Obrazky"',
        '  konec',
        'konec',
        '',
        'oddelovac',
        'text "Stiskni Ctrl+Enter a stranka se hned obnovi."'
      ].join('\n')
    },
    {
      nazev: '2 - Tlacitko, ktere neco udela',
      kod: [
        'stranka "Tlacitko"',
        'vzhled tmavy',
        'zarovnani stred',
        '',
        'nadpis "Kolik je ti let?"',
        'vstup #vek "Sem napis svuj vek"',
        'tlacitko "Odeslat" -> odesli',
        '',
        'text #vysledek "Tady se ukaze odpoved."',
        '',
        'akce odesli',
        '  nastav #vysledek "Ahoj, je ti " + #vek + " let."',
        'konec'
      ].join('\n')
    },
    {
      nazev: '3 - Hra: hadej cislo',
      kod: [
        '// Mala hra na 20 radku.',
        'stranka "Hadej cislo"',
        'vzhled barevny',
        'zarovnani stred',
        '',
        'nadpis "Hadej cislo 1 az 10"',
        'text "Myslim si cislo. Napis ho a stiskni Zkusit."',
        '',
        'karta',
        '  vstup #tip "Tvoje cislo"',
        '  tlacitko "Zkusit" -> zkus',
        '  tlacitko "Nove cislo" -> nova',
        '  text #vysledek ""',
        'konec',
        '',
        'promenna $tajne = nahodne(1, 10)',
        '',
        'akce zkus',
        '  kdyz #tip = $tajne',
        '    nastav #vysledek "Uhodl jsi! Bylo to " + $tajne',
        '  jinak',
        '    kdyz #tip < $tajne',
        '      nastav #vysledek "Moc nizko, zkus vyssi cislo."',
        '    jinak',
        '      nastav #vysledek "Moc vysoko, zkus nizsi cislo."',
        '    konec',
        '  konec',
        'konec',
        '',
        'akce nova',
        '  nastav $tajne nahodne(1, 10)',
        '  nastav #vysledek "Myslim nove cislo. Zkus to znovu!"',
        'konec'
      ].join('\n')
    },
    {
      nazev: '4 - Kalkulacka (aplikace)',
      kod: [
        'stranka "Kalkulacka"',
        'vzhled svetly',
        '',
        'nadpis "Kalkulacka"',
        'text "Napis dve cisla a vyber pocetni operaci."',
        '',
        'karta',
        '  vstup #a "Prvni cislo"',
        '  vstup #b "Druhe cislo"',
        '  tlacitko "Secti" -> secti',
        '  tlacitko "Odecti" -> odecti',
        '  tlacitko "Vynasob" -> vynasob',
        '  text #vysledek "Vysledek se ukaze tady."',
        'konec',
        '',
        'akce secti',
        '  nastav #vysledek "Soucet je " + (#a + #b)',
        'konec',
        '',
        'akce odecti',
        '  nastav #vysledek "Rozdil je " + (#a - #b)',
        'konec',
        '',
        'akce vynasob',
        '  nastav #vysledek "Soucin je " + (#a * #b)',
        'konec'
      ].join('\n')
    },
    {
      nazev: '5 - Poznamkovy blok (aplikace)',
      kod: [
        '// Aplikace, ktera si pamatuje, co do ni napises.',
        'stranka "Poznamkovy blok"',
        'vzhled svetly',
        '',
        'nadpis "Poznamkovy blok"',
        'text "Napis poznamku, zaskrtni ji a uloz."',
        '',
        'karta',
        '  vstup #poznamka "Sem napis poznamku"',
        '  zaskrtavatko #dulezite "Je to dulezite"',
        '  tlacitko "Ulozit" -> uloz',
        '  tlacitko "Nacist" -> nacti',
        '  text #stav "Zatim nic ulozeneho."',
        'konec',
        '',
        'akce uloz',
        '  kdyz #dulezite = 1',
        '    zapis "poznamka" ("DULEZITE: " + #poznamka)',
        '  jinak',
        '    zapis "poznamka" #poznamka',
        '  konec',
        '  nastav #stav "Ulozeno do prohlizece."',
        'konec',
        '',
        'akce nacti',
        '  nacti $text "poznamka"',
        '  nastav #poznamka $text',
        '  nastav #stav "Nacteno. Zkus stranku zavrit a znovu otevrit."',
        'konec'
      ].join('\n')
    },
    {
      nazev: '6 - Posouvej kostku (hra)',
      kod: [
        '// Mala hra: ovladej kostku tlacitky nebo klavesami A, D, W, S.',
        'stranka "Posouvej kostku"',
        'vzhled barevny',
        'zarovnani stred',
        '',
        'nadpis "Posouvej kostku"',
        'text "Stiskni tlacitko nebo klavesu. Kostka se posune."',
        '',
        'karta',
        '  text #kostka "KOSTKA"',
        '  mezera',
        '  tlacitko "Vlevo" -> vlevo',
        '  tlacitko "Doprava" -> vpravo',
        '  tlacitko "Nahoru" -> nahoru',
        '  tlacitko "Dolu" -> dolu',
        '  text #vysledek "Zacni klavesou A."',
        'konec',
        '',
        'klavesa "a" vlevo',
        'klavesa "d" vpravo',
        'klavesa "w" nahoru',
        'klavesa "s" dolu',
        '',
        'akce vlevo',
        '  posun #kostka -40, 0',
        '  nastav #vysledek "Doleva."',
        'konec',
        '',
        'akce vpravo',
        '  posun #kostka 40, 0',
        '  nastav #vysledek "Doprava."',
        'konec',
        '',
        'akce nahoru',
        '  posun #kostka 0, -40',
        '  nastav #vysledek "Nahoru."',
        'konec',
        '',
        'akce dolu',
        '  posun #kostka 0, 40',
        '  nastav #vysledek "Dolu."',
        'konec'
      ].join('\n')
    },
    {
      nazev: '7 - Vizitka s barvami',
      kod: [
        'stranka "Petr Novak - vizitka"',
        'vzhled minimal',
        'barva-pozadi bila',
        '',
        'nadpis #jmeno "Petr Novak"',
        'podnadpis "Student a zacatecnik v programovani"',
        'oddelovac',
        '',
        'karta',
        '  text "Ucim se delat weby a hry. Bavi me fotbal a hry na pocitaci."',
        '  odkaz "Napis mi e-mail" -> "mailto:petr@example.com"',
        'konec',
        '',
        'podnadpis "Moje dovednosti"',
        'seznam',
        '  polozka "CeskyWeb - zacinam"',
        '  polozka "Anglictina - stredne pokrocily"',
        '  polozka "Matematika - dobra"',
        'konec',
        '',
        'tlacitko "Prebarvi nadpis" -> prebarvi',
        '',
        'akce prebarvi',
        '  obarvi #jmeno modra',
        'konec'
      ].join('\n')
    },
    {
      nazev: '8 - Klikaci hra (pocitadlo)',
      kod: [
        '// Hra, ve ktere klikas na tlacitko a pocitas body.',
        'stranka "Moje klikaci hra"',
        'vzhled barevny',
        'zarovnani stred',
        '',
        'nadpis Klikni co nejvickrat',
        'text #skore 0',
        '',
        'tlacitko "Klikni" -> klik',
        'tlacitko "Ulozit" -> uloz',
        'tlacitko "Nacist" -> nacti',
        '',
        'promenna $body = 0',
        '',
        'akce klik',
        '  nastav $body $body + 1',
        '  nastav #skore $body',
        '  obarvi #skore nahodne-barva()',
        'konec',
        '',
        'akce uloz',
        '  zapis "body" $body',
        '  nastav #skore "Ulozeno! Zkus stranku zavrit a znovu otevrit."',
        'konec',
        '',
        'akce nacti',
        '  nacti $body "body"',
        '  nastav #skore $body',
        'konec'
      ].join('\n')
    },
    {
      nazev: '9 - Kresleni na platno',
      kod: [
        '// Kresleni tvary na platno pomoci prikazu.',
        'stranka "Kresleni"',
        'vzhled svetly',
        'zarovnani stred',
        '',
        'nadpis Kreslime na platno',
        'text Zmackni tlacitka a neco se nakresli.',
        '',
        'platno #kresba 400, 300',
        '',
        'tlacitko "Modry ctverec" -> ctverec',
        'tlacitko "Cerveny kruh" -> kruh',
        'tlacitko "Zelena cara" -> cara',
        'tlacitko "Smazat" -> vsechno-smazat',
        '',
        'akce ctverec',
        '  barva-platna #kresba modra',
        '  obdelnik #kresba 20, 20, 120, 80',
        'konec',
        '',
        'akce kruh',
        '  barva-platna #kresba cervena',
        '  kruh #kresba 250, 80, 50',
        'konec',
        '',
        'akce cara',
        '  barva-platna #kresba zelena',
        '  tloustka #kresba 5',
        '  cara #kresba 0, 250, 400, 280',
        'konec',
        '',
        'akce vsechno-smazat',
        '  vycisti #kresba',
        'konec'
      ].join('\n')
    },
    {
      nazev: '10 - Web s menu a komponentami',
      kod: [
        '// Vicestrankovy web. Menu se udela samo prikazem menu.',
        'stranka "Muj web"',
        'vzhled svetly',
        '',
        '// Stavebni blok. Vlozime ho na dvou mistech, pise se jen jednou.',
        'komponenta pata',
        '  oddelovac',
        '  text (c) 2026 Muj web',
        'konec',
        '',
        'menu',
        '',
        'nadpis Vitej',
        'text Tohle je uvodni stranka. Nahore si klikni na O nas nebo Kontakt.',
        'vloz pata',
        '',
        'podstranka #o-nas O nas',
        '  nadpis Kdo jsme',
        '  text Jsme mala firma z Prahy a delame weby.',
        '  vloz pata',
        'konec',
        '',
        'podstranka #kontakt Kontakt',
        '  nadpis Napis nam',
        '  text E-mail: info@mujweb.cz',
        '  tlacitko Zpet na uvod -> domov',
        'konec',
        '',
        'akce domov',
        '  jdi-na #uvod',
        'konec'
      ].join('\n')
    }
  ]
};
